# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


fib_seq = [1]
fib_seq_even = []

i = 0
x = 2
while x < 4000000:
    fib_seq.append(x)
    x = x + fib_seq[i]
    i += 1
    if fib_seq[i] % 2 == 0:
        fib_seq_even.append(fib_seq[i])


print(fib_seq)
print(fib_seq_even)
print(sum(fib_seq_even))

# Answer:  4613732
# Completed on Sun, 31 Aug 2025, 12:05