# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


fib_seq = [1]
fib_seq_even = []

i = 0
x = 2
while x < 4000000:
    fib_seq.append(x)
    x = x + fib_seq[i]
    i += 1
    if fib_seq[i] % 2 == 0:
        fib_seq_even.append(fib_seq[i])

print(fib_seq)
print(fib_seq_even)
print(sum(fib_seq_even))

# OPTIMIZATION TODO:
# - [easy] Re-solve using a different loop structure while clearly tracking each Fibonacci term.
# - [medium] Refactor into a reusable function that accepts any maximum Fibonacci value.
# - [hard] Optimize by generating only even Fibonacci numbers instead of checking every term.

# UPDATE LOG:
# 1.0.0 (2025-08-31) [solved] – Solved problem and confirmed answer: 4613732.
